=== bananapowaa88/BQCMAUxmlGyak/XMLFeladatBQCMAU/XMLSchemaBQCMAU.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="adatbazis">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="telep">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="cim">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:short" name="irSzam"> </xs:element>
                    <xs:element type="xs:string" name="telepules"> </xs:element>
                    <xs:element type="xs:string" name="utca"> </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:byte" name="id"> </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element name="gazda" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="nev"> </xs:element>
              <xs:element type="xs:short" name="fizetes"> </xs:element>
              <xs:element type="xs:byte" name="kor"> </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:byte" name="id" use="optional"> </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element name="kezeltAllat" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="betegseg"> </xs:element>
              <xs:element type="xs:string" name="allatNev"> </xs:element>
              <xs:element type="xs:string" name="eloallitottTermek"> </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:short" name="id" use="optional"> </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element name="alkalmGyogyszer" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:byte" name="mennyiseg"> </xs:element>
              <xs:element type="xs:int" name="ar"> </xs:element>
              <xs:element type="xs:string" name="megnevezes"> </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:short" name="id" use="optional"> </xs:attribute>
          </xs:complexType>
        </xs:element>
        <xs:element name="alkalmazas" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="alkalmazasModja"> </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:short" name="kezeltAllatId" use="optional"> </xs:attribute>
            <xs:attribute type="xs:short" name="gyogyszerId" use="optional"> </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== bananapowaa88/BQCMAUxmlGyak/XMLFeladatBQCMAU/XMLBQCMAU.xml
<?xml version="1.0" encoding="UTF-8"?>

<adatbazis
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="C:\Users\Pirella\eclipse-workspace\DOMParseBQCMAU\src\hu\domparse\bqcmau\XMLSchemaBQCMAU.xsd">
	<telep id="01">
		<cim>
			<irSzam>3535</irSzam>
			<telepules>Budapest</telepules>
			<utca>Kutya</utca>
		</cim>
	</telep>
	<gazda id="001">
		<nev>Péter</nev>
		<fizetes>1000</fizetes>
		<kor>32</kor>
	</gazda>

	<gazda id="002">
		<nev>István</nev>
		<fizetes>2000</fizetes>
		<kor>35</kor>
	</gazda>

	<kezeltAllat id="1000">
		<betegseg>Megfázás</betegseg>
		<allatNev>Sertés</allatNev>
		<eloallitottTermek>Hús</eloallitottTermek>
	</kezeltAllat>

	<kezeltAllat id="1001">
		<betegseg>TBC</betegseg>
		<allatNev>Marha</allatNev>
		<eloallitottTermek>Hús</eloallitottTermek>
	</kezeltAllat>

	<alkalmGyogyszer id="901">
		<mennyiseg>1</mennyiseg>
		<ar>12000</ar>
		<megnevezes>Origo</megnevezes>
	</alkalmGyogyszer>

	<alkalmGyogyszer id="902">
		<mennyiseg>2</mennyiseg>
		<ar>35000</ar>
		<megnevezes>Sentor</megnevezes>
	</alkalmGyogyszer>

	<alkalmazas kezeltAllatId="1000" gyogyszerId="901">
		<alkalmazasModja>injekció</alkalmazasModja>
	</alkalmazas>

	<alkalmazas kezeltAllatId="1001" gyogyszerId="902">
		<alkalmazasModja>tabletta</alkalmazasModja>
	</alkalmazas>
</adatbazis>
